{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 0,
   "metadata": {
    "application/vnd.databricks.v1+cell": {
     "cellMetadata": {},
     "inputWidgets": {},
     "nuid": "bf696721-11d8-4521-b4e8-e5f57df5fe42",
     "showTitle": false,
     "tableResultSettingsMap": {},
     "title": ""
    }
   },
   "outputs": [],
   "source": [
    "import json\n",
    "from pyspark.sql import functions as F\n",
    "from pyspark.sql.types import (StructType, StructField, StringType,\n",
    "                                IntegerType, ArrayType)\n",
    "\n",
    "label_schema = StructType([\n",
    "    StructField(\"drug_brand\", StringType()),\n",
    "    StructField(\"drug_generic\", StringType()),\n",
    "    StructField(\"manufacturer\", StringType()),\n",
    "    StructField(\"warnings\", StringType()),\n",
    "    StructField(\"adverse_reactions\", StringType()),\n",
    "    StructField(\"contraindications\", StringType()),\n",
    "    StructField(\"drug_interactions\", StringType()),\n",
    "    StructField(\"dosage_and_administration\", StringType()),\n",
    "    StructField(\"warnings_and_cautions\", StringType()),\n",
    "    StructField(\"boxed_warning\", StringType()),\n",
    "])\n",
    "\n",
    "def parse_label(payload_json):\n",
    "    p = json.loads(payload_json)\n",
    "    openfda = p.get(\"openfda\", {}) or {}\n",
    "    def first(d, k):\n",
    "        v = d.get(k)\n",
    "        return v[0] if isinstance(v, list) and v else None\n",
    "    def join_field(k):\n",
    "        v = p.get(k)\n",
    "        if isinstance(v, list):\n",
    "            return \" \".join(str(x) for x in v).strip() or None\n",
    "        return v\n",
    "    return {\n",
    "        \"drug_brand\": first(openfda, \"brand_name\"),\n",
    "        \"drug_generic\": first(openfda, \"generic_name\"),\n",
    "        \"manufacturer\": first(openfda, \"manufacturer_name\"),\n",
    "        \"warnings\": join_field(\"warnings\"),\n",
    "        \"adverse_reactions\": join_field(\"adverse_reactions\"),\n",
    "        \"contraindications\": join_field(\"contraindications\"),\n",
    "        \"drug_interactions\": join_field(\"drug_interactions\"),\n",
    "        \"dosage_and_administration\": join_field(\"dosage_and_administration\"),\n",
    "        \"warnings_and_cautions\": join_field(\"warnings_and_cautions\"),\n",
    "        \"boxed_warning\": join_field(\"boxed_warning\"),\n",
    "    }\n",
    "\n",
    "event_schema = StructType([\n",
    "    StructField(\"safetyreportid\", StringType()),\n",
    "    StructField(\"drug_name\", StringType()),\n",
    "    StructField(\"patient_age\", IntegerType()),\n",
    "    StructField(\"patient_sex\", StringType()),\n",
    "    StructField(\"serious\", StringType()),\n",
    "    StructField(\"reactions\", ArrayType(StringType())),\n",
    "    StructField(\"receive_date\", StringType()),\n",
    "])\n",
    "\n",
    "SEX_MAP = {\"1\": \"male\", \"2\": \"female\", \"0\": \"unknown\"}\n",
    "\n",
    "def parse_event(payload_json):\n",
    "    p = json.loads(payload_json)\n",
    "    patient = p.get(\"patient\", {}) or {}\n",
    "    drugs = patient.get(\"drug\", []) or []\n",
    "    drug_name = drugs[0].get(\"medicinalproduct\") if drugs else None\n",
    "    reactions = [r.get(\"reactionmeddrapt\") for r in patient.get(\"reaction\", [])\n",
    "                 if r.get(\"reactionmeddrapt\")]\n",
    "    age_raw = patient.get(\"patientonsetage\")\n",
    "    try:\n",
    "        age = int(age_raw) if age_raw is not None else None\n",
    "    except (ValueError, TypeError):\n",
    "        age = None\n",
    "    return {\n",
    "        \"safetyreportid\": p.get(\"safetyreportid\"),\n",
    "        \"drug_name\": drug_name,\n",
    "        \"patient_age\": age,\n",
    "        \"patient_sex\": SEX_MAP.get(str(patient.get(\"patientsex\", \"\")), \"unknown\"),\n",
    "        \"serious\": p.get(\"serious\"),\n",
    "        \"reactions\": reactions,\n",
    "        \"receive_date\": p.get(\"receivedate\"),\n",
    "    }\n",
    "\n",
    "parse_label_udf = F.udf(parse_label, label_schema)\n",
    "parse_event_udf = F.udf(parse_event, event_schema)\n",
    "\n",
    "bronze = spark.table(\"fda_rag.bronze.openfda_raw\")\n",
    "\n",
    "silver_labels = (bronze.filter(F.col(\"source\") == \"label\")\n",
    "    .withColumn(\"parsed\", parse_label_udf(\"payload\"))\n",
    "    .select(\"drug\", \"parsed.*\", F.current_timestamp().alias(\"ingested_at\"))\n",
    "    .filter(F.col(\"drug_generic\").isNotNull())\n",
    "    .dropDuplicates([\"drug_generic\", \"manufacturer\"]))\n",
    "\n",
    "(silver_labels.write.mode(\"overwrite\")\n",
    "    .option(\"overwriteSchema\", \"true\")\n",
    "    .saveAsTable(\"fda_rag.silver.drug_labels\"))\n",
    "\n",
    "silver_events = (bronze.filter(F.col(\"source\") == \"event\")\n",
    "    .withColumn(\"parsed\", parse_event_udf(\"payload\"))\n",
    "    .select(\"drug\", \"parsed.*\", F.current_timestamp().alias(\"ingested_at\"))\n",
    "    .filter(F.col(\"safetyreportid\").isNotNull())\n",
    "    .filter(F.size(\"reactions\") > 0)\n",
    "    .dropDuplicates([\"safetyreportid\"]))\n",
    "\n",
    "(silver_events.write.mode(\"overwrite\")\n",
    "    .option(\"overwriteSchema\", \"true\")\n",
    "    .saveAsTable(\"fda_rag.silver.adverse_events\"))\n",
    "\n",
    "print(\"Silver:\")\n",
    "print(f\"  drug_labels:    {spark.table('fda_rag.silver.drug_labels').count()}\")\n",
    "print(f\"  adverse_events: {spark.table('fda_rag.silver.adverse_events').count()}\")"
   ]
  }
 ],
 "metadata": {
  "application/vnd.databricks.v1+notebook": {
   "computePreferences": null,
   "dashboards": [],
   "environmentMetadata": {
    "base_environment": "",
    "environment_version": "5"
   },
   "inputWidgetPreferences": null,
   "language": "python",
   "notebookMetadata": {
    "pythonIndentUnit": 4
   },
   "notebookName": "02a_silver.py",
   "widgets": {}
  },
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}
