{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {
    "application/vnd.databricks.v1+cell": {
     "cellMetadata": {},
     "inputWidgets": {},
     "nuid": "57b9e7d0-6482-45f6-aeec-eff121aff711",
     "showTitle": false,
     "tableResultSettingsMap": {},
     "title": ""
    }
   },
   "source": [
    "Gold — Analytics projection (star schema)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 0,
   "metadata": {
    "application/vnd.databricks.v1+cell": {
     "cellMetadata": {},
     "inputWidgets": {},
     "nuid": "bcf2e5d3-cffa-4702-b0cb-d40f85b28bde",
     "showTitle": false,
     "tableResultSettingsMap": {},
     "title": ""
    }
   },
   "outputs": [],
   "source": [
    "from pyspark.sql import functions as F\n",
    "\n",
    "labels = spark.table(\"fda_rag.silver.drug_labels\")\n",
    "events = spark.table(\"fda_rag.silver.adverse_events\")\n",
    "\n",
    "# ---------- dim_drug ----------\n",
    "drugs_from_labels = (labels.select(\n",
    "        F.lower(F.col(\"drug_generic\")).alias(\"drug_generic\"),\n",
    "        F.col(\"drug_brand\"), F.col(\"manufacturer\"))\n",
    "    .filter(F.col(\"drug_generic\").isNotNull()))\n",
    "\n",
    "drugs_from_events = (events.select(\n",
    "        F.lower(F.col(\"drug_name\")).alias(\"drug_generic\"),\n",
    "        F.lit(None).cast(\"string\").alias(\"drug_brand\"),\n",
    "        F.lit(None).cast(\"string\").alias(\"manufacturer\"))\n",
    "    .filter(F.col(\"drug_generic\").isNotNull()))\n",
    "\n",
    "dim_drug = (drugs_from_labels.unionByName(drugs_from_events)\n",
    "    .groupBy(\"drug_generic\")\n",
    "    .agg(F.first(\"drug_brand\", ignorenulls=True).alias(\"drug_brand\"),\n",
    "         F.first(\"manufacturer\", ignorenulls=True).alias(\"manufacturer\"))\n",
    "    .withColumn(\"drug_key\", F.sha2(F.col(\"drug_generic\"), 256))\n",
    "    .select(\"drug_key\", \"drug_generic\", \"drug_brand\", \"manufacturer\")\n",
    "    .withColumn(\"loaded_at\", F.current_timestamp()))\n",
    "\n",
    "(dim_drug.write.mode(\"overwrite\").option(\"overwriteSchema\", \"true\")\n",
    "    .saveAsTable(\"fda_rag.gold.dim_drug\"))\n",
    "\n",
    "# ---------- dim_patient ----------\n",
    "def age_band(c):\n",
    "    return (F.when(c.isNull(), \"unknown\")\n",
    "             .when(c < 18, \"0-17\").when(c < 45, \"18-44\")\n",
    "             .when(c < 65, \"45-64\").when(c < 75, \"65-74\")\n",
    "             .otherwise(\"75+\"))\n",
    "\n",
    "dim_patient = (events\n",
    "    .select(age_band(F.col(\"patient_age\")).alias(\"age_band\"),\n",
    "            F.coalesce(F.col(\"patient_sex\"), F.lit(\"unknown\")).alias(\"sex\"))\n",
    "    .distinct()\n",
    "    .withColumn(\"patient_key\",\n",
    "        F.sha2(F.concat_ws(\"|\", \"age_band\", \"sex\"), 256))\n",
    "    .select(\"patient_key\", \"age_band\", \"sex\")\n",
    "    .withColumn(\"loaded_at\", F.current_timestamp()))\n",
    "\n",
    "(dim_patient.write.mode(\"overwrite\").option(\"overwriteSchema\", \"true\")\n",
    "    .saveAsTable(\"fda_rag.gold.dim_patient\"))\n",
    "\n",
    "# ---------- dim_reaction ----------\n",
    "BODY_SYSTEMS = {\n",
    "    \"cardiac\": [\"cardiac\", \"heart\", \"myocardial\", \"arrhythmia\",\n",
    "                \"tachycardia\", \"bradycardia\", \"hypertension\", \"hypotension\"],\n",
    "    \"gastrointestinal\": [\"nausea\", \"vomiting\", \"diarrhoea\", \"diarrhea\",\n",
    "                          \"abdominal\", \"gastric\", \"constipation\"],\n",
    "    \"neurological\": [\"headache\", \"dizziness\", \"seizure\", \"tremor\",\n",
    "                      \"neuropathy\", \"paraesthesia\"],\n",
    "    \"hepatic\": [\"hepatic\", \"liver\", \"jaundice\", \"transaminase\"],\n",
    "    \"renal\": [\"renal\", \"kidney\", \"creatinine\"],\n",
    "    \"dermatological\": [\"rash\", \"pruritus\", \"urticaria\", \"dermatitis\"],\n",
    "    \"respiratory\": [\"dyspnoea\", \"dyspnea\", \"cough\", \"asthma\", \"pulmonary\"],\n",
    "    \"haematological\": [\"anaemia\", \"anemia\", \"thrombocytopenia\",\n",
    "                        \"leukopenia\", \"bleeding\", \"haemorrhage\"],\n",
    "}\n",
    "\n",
    "def classify(col):\n",
    "    expr = F.lit(\"other\")\n",
    "    for system, kws in BODY_SYSTEMS.items():\n",
    "        cond = F.lit(False)\n",
    "        for kw in kws:\n",
    "            cond = cond | F.lower(col).contains(kw)\n",
    "        expr = F.when(cond, system).otherwise(expr)\n",
    "    return expr\n",
    "\n",
    "dim_reaction = (events\n",
    "    .select(F.explode(\"reactions\").alias(\"reaction_term\"))\n",
    "    .filter(F.col(\"reaction_term\").isNotNull())\n",
    "    .select(F.lower(F.col(\"reaction_term\")).alias(\"reaction_term\"))\n",
    "    .distinct()\n",
    "    .withColumn(\"body_system\", classify(F.col(\"reaction_term\")))\n",
    "    .withColumn(\"reaction_key\", F.sha2(F.col(\"reaction_term\"), 256))\n",
    "    .select(\"reaction_key\", \"reaction_term\", \"body_system\")\n",
    "    .withColumn(\"loaded_at\", F.current_timestamp()))\n",
    "\n",
    "(dim_reaction.write.mode(\"overwrite\").option(\"overwriteSchema\", \"true\")\n",
    "    .saveAsTable(\"fda_rag.gold.dim_reaction\"))\n",
    "\n",
    "# ---------- dim_date ----------\n",
    "bounds = (events.select(F.to_date(\"receive_date\", \"yyyyMMdd\").alias(\"d\"))\n",
    "    .filter(F.col(\"d\").isNotNull())\n",
    "    .agg(F.min(\"d\").alias(\"min_d\"), F.max(\"d\").alias(\"max_d\"))\n",
    "    .collect()[0])\n",
    "\n",
    "dim_date = (spark.sql(f\"\"\"\n",
    "    SELECT explode(sequence(\n",
    "        to_date('{bounds['min_d']}'),\n",
    "        to_date('{bounds['max_d']}'),\n",
    "        interval 1 day)) AS full_date\n",
    "    \"\"\")\n",
    "    .withColumn(\"date_key\", F.date_format(\"full_date\", \"yyyyMMdd\").cast(\"int\"))\n",
    "    .withColumn(\"year\", F.year(\"full_date\"))\n",
    "    .withColumn(\"quarter\", F.quarter(\"full_date\"))\n",
    "    .withColumn(\"month\", F.month(\"full_date\"))\n",
    "    .withColumn(\"month_name\", F.date_format(\"full_date\", \"MMMM\"))\n",
    "    .withColumn(\"day_of_week\", F.date_format(\"full_date\", \"EEEE\"))\n",
    "    .select(\"date_key\", \"full_date\", \"year\", \"quarter\",\n",
    "            \"month\", \"month_name\", \"day_of_week\"))\n",
    "\n",
    "(dim_date.write.mode(\"overwrite\").option(\"overwriteSchema\", \"true\")\n",
    "    .saveAsTable(\"fda_rag.gold.dim_date\"))\n",
    "\n",
    "# ---------- fact_adverse_event ----------\n",
    "exploded = (events\n",
    "    .withColumn(\"reaction_term\", F.explode(\"reactions\"))\n",
    "    .select(\n",
    "        F.col(\"safetyreportid\"),\n",
    "        F.lower(F.col(\"drug_name\")).alias(\"drug_generic\"),\n",
    "        F.lower(F.col(\"reaction_term\")).alias(\"reaction_term\"),\n",
    "        F.col(\"patient_age\"), F.col(\"patient_sex\"), F.col(\"serious\"),\n",
    "        F.to_date(\"receive_date\", \"yyyyMMdd\").alias(\"event_date\"))\n",
    "    .filter(F.col(\"reaction_term\").isNotNull()))\n",
    "\n",
    "exploded = (exploded\n",
    "    .withColumn(\"age_band\", age_band(F.col(\"patient_age\")))\n",
    "    .withColumn(\"sex\", F.coalesce(F.col(\"patient_sex\"), F.lit(\"unknown\"))))\n",
    "\n",
    "fact = (exploded\n",
    "    .join(dim_drug.select(\"drug_key\", \"drug_generic\"),\n",
    "          on=\"drug_generic\", how=\"left\")\n",
    "    .join(dim_reaction.select(\"reaction_key\", \"reaction_term\"),\n",
    "          on=\"reaction_term\", how=\"left\")\n",
    "    .join(dim_patient.select(\"patient_key\", \"age_band\", \"sex\"),\n",
    "          on=[\"age_band\", \"sex\"], how=\"left\")\n",
    "    .withColumn(\"date_key\",\n",
    "        F.date_format(\"event_date\", \"yyyyMMdd\").cast(\"int\"))\n",
    "    .select(\n",
    "        F.col(\"safetyreportid\").alias(\"report_id\"),\n",
    "        \"drug_key\", \"reaction_key\", \"patient_key\", \"date_key\",\n",
    "        F.when(F.col(\"serious\") == \"1\", 1).otherwise(0).alias(\"is_serious\"),\n",
    "        F.lit(1).alias(\"reaction_count\"))\n",
    "    .filter(F.col(\"drug_key\").isNotNull())\n",
    "    .filter(F.col(\"reaction_key\").isNotNull()))\n",
    "\n",
    "(fact.write.mode(\"overwrite\").option(\"overwriteSchema\", \"true\")\n",
    "    .partitionBy(\"date_key\")\n",
    "    .saveAsTable(\"fda_rag.gold.fact_adverse_event\"))\n",
    "\n",
    "print(\"Analytics gold:\")\n",
    "for t in [\"dim_drug\", \"dim_patient\", \"dim_reaction\", \"dim_date\", \"fact_adverse_event\"]:\n",
    "    print(f\"  {t}: {spark.table(f'fda_rag.gold.{t}').count()}\")"
   ]
  }
 ],
 "metadata": {
  "application/vnd.databricks.v1+notebook": {
   "computePreferences": null,
   "dashboards": [],
   "environmentMetadata": {
    "base_environment": "",
    "environment_version": "5"
   },
   "inputWidgetPreferences": null,
   "language": "python",
   "notebookMetadata": {
    "pythonIndentUnit": 4
   },
   "notebookName": "02c_gold_analytics.py",
   "widgets": {}
  },
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}
